### ISSUE TITLE
Hop length

### ISSUE THREAD

**Issue by Psarpei** [lucidrains/BS-RoFormer#11]
I am still a bit confused because in the code is the following comment 
in line 241 `stft_hop_length = 512, # 10ms at 44100Hz, from sections 4.1, 4.4 in the paper - @faroit recommends // 2 or // 4 for better `

It's true that they are mentioned to use a hop_size of 10ms for a 44.1kHz sample rate, but in my calculation 512 is not 10ms but ~11.6ms

Did I missunderstood something or what is the intention here ?

**Comment by faroit** [comment]
@Psarpei 512 is just a lot more common. Also torch istft and stft is slow so I suggest to not make it slower with non power of 2 values.

**Comment by Psarpei** [comment]
Okay thanks for your answer :) but than there is the problem that the resulting audio length will not match the original one. What is your suggestion to handle that?

**Comment by iver56** [comment]
Not all lengths are compatible. Check the length of the output you are getting and use that as the input length.

**Comment by Psarpei** [comment]
but in that way I loose information at the end of the audio, how do you avoid that using this approach ?

**Comment by iver56** [comment]
If you use a compatible length, the length of the output will be the same as the length of the input. You are not losing anything this way. If you need to apply it to longer audio snippets, check out the part of the paper that describes overlap-add (OA) as one of several viable techniques.

**Comment by Psarpei** [comment]
okay thanks :)
