### ISSUE TITLE
Hidden dim in mask estimation module

### ISSUE THREAD

**Issue by Psarpei** [lucidrains/BS-RoFormer#12]
In the paper second sentence in 4.4 configuration they mention:
> The multi-band mask estimation module utilizes MLPs with a hidden layer dimension of 4D.

But in the actual code from my understanding there is no hidden layer only 2 linear layers smart combined to a single one.

**Comment by lucidrains** [comment]
@Psarpei ah yea, good catch

i've added the hidden layer with the expansion factor of 4

**Comment by Psarpei** [comment]
Nice thanks :)

One last thing, they mention also that they are using a dim size of 384 that would result in a head_dim of 48 for 8 heads. In the actual code the head_dim is 64, If the Implementation should allign the one from the paper one could also consider to change the head_dim to 48

**Comment by lucidrains** [comment]
@Psarpei yeah, you can simply set `dim_head = 48` [here](https://github.com/lucidrains/BS-RoFormer/blob/main/bs_roformer/bs_roformer.py#L240) 64 would not hurt

**Comment by lucidrains** [comment]
@Psarpei the dim size is actually independent of attention head dimension, if implemented correctly

**Comment by Psarpei** [comment]
Okay thanks :)

**Comment by lucidrains** [comment]
you doing ML consulting work for accenture? i used to know a couple ex-accenture consultants
