### ISSUE TITLE
How to use it for audio source separation?

### ISSUE THREAD

**Issue by asasas234** [lucidrains/BS-RoFormer#14]
I am a novice in this field and would like to complete the task of audio source separation. This project seems to be for that purpose, but I couldn't understand how to use it for audio source separation based on the examples in the documentation.

**Comment by lucidrains** [comment]
@asasas234 if you are a beginner, you can see if a deep learning practitioner is willing to do some hand holding [here](https://github.com/lucidrains/BS-RoFormer/discussions/18)

**Comment by lucidrains** [comment]
@asasas234 would also recommend the Laion community, linked in the readme
