### ISSUE TITLE
Linear Attention temperature initialization

### ISSUE THREAD

**Issue by f0k** [lucidrains/BS-RoFormer#28]
First of all, thanks for all the good work (including in this repo)!

There's a potential bug in LinearAttention that I thought I should bring to your attention: In contrast to the [original paper](https://github.com/facebookresearch/xcit/blob/main/detection/backbone/xcit.py#L256), you learn the logarithmic temperature, but still initialize the parameter [with ones](https://github.com/lucidrains/BS-RoFormer/blob/8f5f52a/bs_roformer/mel_band_roformer.py#L147) instead of zeros. This means the temperature will initially be Euler's number. Maybe it doesn't make much of a difference in practice or works even better, but it looks like it may have been unintentional.

**Comment by lucidrains** [comment]
@f0k thanks Jan! made the change
