### ISSUE TITLE
Flash attention error in Linear Attention layer

### ISSUE THREAD

**Issue by ZFTurbo** [lucidrains/BS-RoFormer#29]
I noticed error in Linear Attention layer when `flash_attn` is set in `True`:

```
File "attend.py", line 84, in flash_attn
    out = F.scaled_dot_product_attention(
RuntimeError: No available kernel. Aborting execution. 
```

In standard Attention (`time_transformer` and `freq_transformer`) it works ok.

So currently as workaround I did followig change in `LinearAttention` (set False to flash):

```
self.attend = Attend(
    scale=scale,
    dropout=dropout,
    flash=False
)
```

**Comment by lucidrains** [comment]
@ZFTurbo ohh ok, i've made it configurable using `linear_flash_attn` kwarg
