### ISSUE TITLE
Reproduce the results from the paper

### ISSUE THREAD

**Issue by Andrew98998** [lucidrains/BS-RoFormer#30]
Hi, 

Has anyone successfully reproduced the results from the paper? I am interested in doing more experiments with this architecture.

Thanks!

**Comment by ZFTurbo** [comment]
BS Roformer works very great. Some vocals weights were posted here:
https://github.com/ZFTurbo/Music-Source-Separation-Training?tab=readme-ov-file#vocal-models

Mel Roformer works worse for unknown reason. (SDR 9.67 vs 10.87)
