### ISSUE TITLE
Hi @lucidrains + @ZFTurbo

### ISSUE THREAD

**Issue by MaxCoo** [lucidrains/BS-RoFormer#5]
Hi @lucidrains + @ZFTurbo 

I work with birds and have a audio dataset the sounds they make that I would like to train with this code, I have had success with other models that were authored for music. Please can I request for a way to train this model to be added to the code? Sorry i can not accomplish this myself.

_Originally posted by @lyndonlauder in https://github.com/lucidrains/BS-RoFormer/issues/4#issuecomment-1743172734_

**Comment by lucidrains** [comment]
@MaxCoo yes you can, i believe in you

training is just what i showed in the readme, within a for loop. you can also use a variety of solutions million-dollar startups have tried to simplify for you (hf accelerate, lighting etc)

**Comment by MaxCoo** [comment]
@lucidrains I believe in me. I thank you very much for this implementation.

**Comment by ZFTurbo** [comment]
I published my training code here:
https://github.com/ZFTurbo/Music-Source-Separation-Training

It gives ability to train 5 types of models: mdx23c, htdemucs, vitlarge23, bs_roformer and mel_band_roformer.
I also put some weights there to start training not from the scratch.

**Comment by lucidrains** [comment]
@ZFTurbo thank you Roman for contributing the training code and weights! i've linked to your repository in the readme! 🙏
