### ISSUE TITLE
Default time_transformer_depth

### ISSUE THREAD

**Issue by iver56** [lucidrains/BS-RoFormer#6]
In readme you use the following parameters as example:

```
time_transformer_depth = 1
freq_transformer_depth = 1
```

However, these are the defaults in the BSRoformer class:

```
time_transformer_depth = 2
freq_transformer_depth = 2
```

What would you recommend?

**Comment by lucidrains** [comment]
@iver56 hey, you should just check the paper and see what they used

although knowing attention and transformers, it almost doesn't matter once you scale up and add more data.

**Comment by lucidrains** [comment]
almost all attention breakthroughs rely on data, scale, as well as walking the tightrope of stable training when parameter count passes certain thresholds.

**Comment by lucidrains** [comment]
this hyperparameter should not matter as much as the main depth
